##################################################
#Playbooks: Unistall Apache on CentOS8 AT
##################################################
---
- hosts: nodes
  become: true
  remote_user: ansible

  tasks:
      - name: UNInstall apache(httpd) packages 
        yum:
          name: httpd
          state: latest       
          
      - name: Close port 80 for http access
        firewalld:
          service: http
          permanent: true
          state: disabled  
          
      - name: Close port 443 for https access(optional)
        firewalld:
          service: https
          permanent: true
          state: disabled        
          
      - name: Restart the firewalld service to load in the firewall changes
        service: 
          name: firewalld 
          state: restarted      

 
    - name: Delete index test page
      file:
        state: absent
        path: "/var/www/html/index.html"          