---
- hosts: nodes
  become: true
  remote_user: ansible
  vars_files:
          - files/secret.yml

  tasks:
#    - name: Print PASSWD
#      debug:
#             msg: "PASSWORD {{ vault_db_pass }}"
         
    - name:  Creating user
      user:
            name:  "{{ item.name }}"
            comment: "{{ item.name }}@examle.com"
            state:  present
            password: "{{ vault_db_pass | password_hash('sha512')}}"
            home: "/home/{{ item.name }}"
            update_password: on_create
      loop:
            - name: Alice
            - name: Bob
            - name: Carol
