- hosts:  nodes
  become:  true
  remote_user:  ansible

  tasks:
    - name:  Install apache(httpd) packages 
      yum:
          name:  httpd
          state:  latest   

    - name:  httpd is running on boot up
      service:
              name:  httpd 
              state:  started
              enabled:  yes      

    - name:  Open port 80 for http access
      firewalld:
                service:  http
                permanent:  true
                state:  enabled      

    - name:  Open port 443 for https access(optional)
      firewalld:
                service:  https
                permanent:  true
                state:  enabled        

    - name:  Restart the firewalld service to load in the firewall changes
      service: 
              name:  firewalld 
              state:  restarted   

    - name:  Restart httpd service
      service:
              name:  httpd
              state:  restarted

    - name:  Copy index test page
      copy:
            src:  "files/index.html"
            dest:  "/var/www/html/index.html"      
